version: '3.8'

services:
  app:
    build: .
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - LOG_LEVEL=info
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3002/api/v1/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network

  # Development service (optional)
  app-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3003:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - LOG_LEVEL=debug
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - /app/node_modules
    command: npm run dev
    profiles:
      - dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 